name: 'Get Job Summary'
description: 'Get GitHub Actions job summary URL and other job information'
author: 'Yuki Sakai'
branding:
  icon: 'info'
  color: 'blue'

inputs:
  repository:
    description: 'The owner and repository name (e.g., owner/repo)'
    required: false
    default: ${{ github.repository }}
  server_url:
    description: 'The URL of the GitHub server'
    required: false
    default: ${{ github.server_url }}
  workflow:
    description: 'The name or ID of the workflow'
    required: false
    default: ${{ github.workflow }}
  run_id:
    description: 'The ID of the workflow run'
    required: false
    default: ${{ github.run_id }}
  run_attempt:
    description: 'The attempt number of the workflow run'
    required: false
    default: ${{ github.run_attempt }}
  job:
    description: 'The job name'
    required: false
    default: ${{ github.job }}
  github_token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  include_job_summary_anchor:
    description:
      'Include anchor to specific job in job_summary_url (e.g., #summary-12345)'
    required: false
    default: 'false'

outputs:
  run_url:
    description: 'The URL of the workflow run'
  job_id:
    description: 'The ID of the job'
  job_name:
    description: 'The name of the job'
  job_url:
    description: 'The URL of the job'
  job_summary_url:
    description: 'The URL of the job summary'
  job_summary_raw_url:
    description: 'The raw URL of the job summary'
  job_status:
    description: 'The status of the job'
  job_conclusion:
    description: 'The conclusion of the job'
  job_started_at:
    description: 'When the job started'
  job_completed_at:
    description: 'When the job completed'
  workflow_name:
    description: 'The name of the workflow'
  workflow_path:
    description: 'The path of the workflow file'
  run_number:
    description: 'The run number of the workflow'
  job_summary_content:
    description: 'The text content of the job summary'

runs:
  using: 'node20'
  main: 'dist/index.js'
